sudo: false
language: node_js
before_deploy:
  - npm run build
  - npm run storybook:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: release-25
  local_dir: .storybook-static
